### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by parro-it** [parro-it/libui-napi#1]
Check that they are built on CI only for master branch, and not for PR

**Comment by mischnic** [comment]
https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A:

> ```yaml
>deploy:
>  provider: s3
>  access_key_id: "YOUR AWS ACCESS KEY"
>  secret_access_key: "YOUR AWS SECRET KEY"
>  bucket: "S3 Bucket"
>  skip_cleanup: true
>  on:
>    branch: release # <<------------ HERE
>    condition: $MY_ENV = super_awesome
>```
>
> When all conditions specified in the on: section are met, your build will deploy.

**Comment by parro-it** [comment]
Yes, exactly that, thank you!
