### ISSUE TITLE
Form padding

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-napi#15]
This does nothing:

https://github.com/parro-it/libui-napi/blob/09dda8784a04fc3d93329a73d7edf6b781b7f653/example/forms.js#L27

Will there be setter/getter functions and properties for everything?

**Comment by parro-it** [comment]
Thank you!

**Comment by mischnic** [comment]
Same goes for Box:

https://github.com/parro-it/libui-napi/blob/ae050bf9dc81b60f787dffca8af92989edb27b69/js/box.js#L12-L19

**Comment by parro-it** [comment]
Thank you! Fixed there too...

**Comment by mischnic** [comment]
```
libui-napi/example/widgets/showUiEditableCombobox.js:27
box.setPadded(true);
    ^

TypeError: box.setPadded is not a function
```

and more examples as well...

**Comment by parro-it** [comment]
Fixed them too. But before, all setters and getters function were available in public API. I think we should addd them to JS classes to avoid breaking compatibility.
Do you know if proton-native actually use them?

**Comment by mischnic** [comment]
Only the properties are used there
