### ISSUE TITLE
Internal links in docs pages are broken

### ISSUE THREAD

**Issue by parro-it** [parro-it/libui-napi#26]
E.g. in https://parro-it.github.io/libui-napi/#/group,
the title anchor refer to
> https://parro-it.github.io/libui-napi/#/group?id=uigroup%20title

while the correct one should be 

> https://parro-it.github.io/libui-napi/#/group?id=uigrouptitle-%e2%87%92-string

Not sure if it's a bug in jsdoc-to-markdown or if there's something wrong on our side

**Comment by mischnic** [comment]
None of these table of contents links work on the website.

It works in the GitHub preview: https://github.com/parro-it/libui-napi/blob/master/docs/group.md#UiGroup+title

**Comment by parro-it** [comment]
Oh, I guess it's a bug in the template then? It would be preferable if they work just on the site...

**Comment by mischnic** [comment]
For group it's the template, for horizontal-box some bog (the link looks like this: `[.enabled](#)`).
