### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-napi#4]
https://github.com/parro-it/libui-napi/blob/5c23f0e0f9e8631e69fd68d236a56044f08cc289/src/win_map.c#L1

```
../src/win_map.c:1:10: fatal error: 'window.h' file not found
#include "window.h"
         ^~~~~~~~~~
1 error generated.
```

Should be "control.h" ?

**Comment by parro-it** [comment]
No, "map_template.h".
I fixed it but cannot push now because I'm in the middle of another problem,...

**Comment by parro-it** [comment]
No ,wait, you're right, control.h!
