### ISSUE TITLE
Proper cache directory on macOS

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-napi#49]
The correct cache folder (which is also excluded from Time Machine backups by default) is "\~/Library/Caches/" instead of "\~/.libui_xxx" (also used by npm, Yarn, electron-builder).

Same goes for windows, something like https://www.npmjs.com/package/cachedir ?

**Comment by parro-it** [comment]
Good idea, I added cachedir as you suggested, and remove home-path dependency, not used anymore.
