### ISSUE TITLE
When registering events, we need to remove existing events_node for the same event and support NULL event to only remove event.

### ISSUE THREAD

**Issue by parro-it** [parro-it/libui-napi#5]

**Comment by mischnic** [comment]
```c
struct event_t *create_event(napi_env env, napi_ref cb_ref, const char *name) {
	// ...

	struct event_t *event = calloc(1, sizeof(struct event_t));
	event->cb_ref = cb_ref;
	// ...
}
```

**Comment by parro-it** [comment]
It's only used in debugging at the moment, we can include if in a #if #endif to remove from production.

**Comment by mischnic** [comment]
For this:

> When registering events, we need to remove existing events_node for the same event

it is needed

**Comment by parro-it** [comment]
I plan to use a custom pointer to distinguish events, we can pass the function pointer of the callback.
This is a preferred way because multiple events could have the same name

**Comment by mischnic** [comment]
> This is a preferred way because multiple events could have the same name

Multiple events with the same name on the same control?

**Comment by parro-it** [comment]
> Multiple events with the same name on the same control?

No, obviously not possible, I can't remember why I was planning to use a function pointer...
So I guess using the name would be just fine...
