### ISSUE TITLE
AttributedString forEach return value

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-napi#58]
The return value is ignored (doesn't break with `return true`).

https://github.com/parro-it/libui-napi/blob/aa7e275cfdfbeaf766da091df72179f61a51ce70/docs/attributedstring.md#L131-L138

(Can check this myself later as well, this is just so I won't forget this)

**Comment by parro-it** [comment]
As I'm working on typescripts definitions, I checked the type definitions, it correctly return a boolean

**Comment by mischnic** [comment]
> I checked the type definitions, it correctly return a boolean

This isn't about the defintions. (But the return value is coerced to a boolean, so returning something is optional
https://github.com/parro-it/libui-napi/blob/aa7e275cfdfbeaf766da091df72179f61a51ce70/js/font-string.js#L54
I've changed that in my PR).

Well, it works now. Not sure what I did previously.
